ersion: "3.9"

services:
  api:
    build: .
    container_name: geoia_backend
    restart: always
    env_file: .env
    networks:
      - proxy
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"

      # Router con prefijo /api
      - "traefik.http.routers.geoia-api.rule=Host(`geoia.codeauni.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.geoia-api.entrypoints=websecure"
      - "traefik.http.routers.geoia-api.tls=true"
      - "traefik.http.routers.geoia-api.tls.certresolver=mytlschallenge"

      # Middleware para decirle a FastAPI que el prefijo real es /api
      - "traefik.http.middlewares.geoia-prefix.headers.customrequestheaders.X-Forwarded-Prefix=/api"

      # Solo usamos este middleware (sin stripPrefix, sin CORS Traefik)
      - "traefik.http.routers.geoia-api.middlewares=geoia-prefix"

      # Puerto interno
      - "traefik.http.services.geoia-api.loadbalancer.server.port=8000"

      # Red de Traefik
      - "traefik.docker.network=proxy"

  mongo:
    image: mongo:6
    container_name: geoia_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - proxy
    environment:
      MONGO_INITDB_DATABASE: geoia_db

networks:
  proxy:
    external: true