version: "3.9"

services:
  api:
    image: ghcr.io/arnoldcamposcn/geoia-backend:latest
    container_name: geoia_backend
    restart: always
    env_file: .env
    networks:
      - proxy
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geoia-api.rule=Host(`api.geoia.codeauni.com`)"
      - "traefik.http.routers.geoia-api.entrypoints=websecure"
      - "traefik.http.routers.geoia-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.geoia-api.loadbalancer.server.port=8000"

  mongo:
    image: mongo:6
    container_name: geoia_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - proxy
    environment:
      MONGO_INITDB_DATABASE: geoia_db

networks:
  proxy:
    external: true

volumes:
  mongo_data:
