ersion: "3.9"

services:
  api:
    image: ghcr.io/arnoldcamposcn/geoia-backend:latest
    container_name: geoia_backend
    restart: always
    env_file: .env
    networks:
      - proxy
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      # La regla enruta todo lo que empieza por /api
      - "traefik.http.routers.geoia-api.rule=Host(`geoia.codeauni.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.geoia-api.entrypoints=websecure"
      - "traefik.http.routers.geoia-api.tls=true"
      - "traefik.http.routers.geoia-api.tls.certresolver=mytlschallenge"
      - "traefik.http.services.geoia-api.loadbalancer.server.port=8000"

      # *** SE ELIMINARON las l√≠neas de strip-api, ya que FastAPI usa root_path="/api" ***

  mongo:
    image: mongo:6
    container_name: geoia_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - proxy
    environment:
      MONGO_INITDB_DATABASE: geoia_db

networks:
  proxy:
    external: true

volumes:
  mongo_data: